### ISSUE TITLE
Fix six problems about [L/R]TrimAny library functions.

### ISSUE THREAD

**Issue by skyfish4tb** [freebasic/fbc#116]
Unnecessary multiple lookups:
![l r trim](https://user-images.githubusercontent.com/13896021/49260442-8f2acd80-f478-11e8-9c09-6e9aa965c7ad.jpg)

**Comment by countingpine** [comment]
If you think these changes are worth committing, it might be better to submit this as a pull request.
For what it's worth though, I'm impressed you managed to capture that as a screenshot.  You must have a very tall monitor :)

**Comment by sancarn** [comment]
@countingpine They likely used a scrolling screenshot 😛 At least you can do that with ShareX

**Comment by jayrm** [comment]
@skyfish4tb,
Is https://github.com/skyfish4tb/fbc/commit/0e4c0daa82370965a99ad00aeb96adb458026fe5 the correct commit to be looking at?

The commit message says: "2. The optimization of [L/R]TrimAny function code."

Does the change fix problems?  If yes, what were the failed cases?  
Or this change is only an optimization?

I was working on some issues related to the wstring [L|R]TRIM functions in #142 

Thanks.
