### ISSUE TITLE
"make bootstrap" race condition

### ISSUE THREAD

**Issue by vilhelmgray** [freebasic/fbc#131]
The following error occurs when building from the [FreeBasic-1.06.0-source-bootstrap.tar.xz](https://github.com/freebasic/fbc/releases/download/1.06.0/FreeBASIC-1.06.0-source-bootstrap.tar.xz) source code:

    LINK bootstrap/fbc
    AR lib/freebasic/linux-x86_64/libfb.a
    gcc: error: lib/freebasic/linux-x86_64/libfb.a: No such file or directory
    AR lib/freebasic/linux-x86_64/libfbpic.a
    make: *** [makefile:1093: bootstrap/fbc] Error 1
    make: *** Waiting for unfinished jobs....
    AR lib/freebasic/linux-x86_64/libfbmt.a

The following command was used to run the build:

    make -j5 bootstrap CFLAGS="-DDISABLE_X11 -DDISABLE_GPM -DDISABLE_FFI -DDISABLE_OPENGL"

I suspect this is a race condition issue, because the issue disappears when the number of make jobs is restricted to 1:

    make -j1 bootstrap CFLAGS="-DDISABLE_X11 -DDISABLE_GPM -DDISABLE_FFI -DDISABLE_OPENGL"

On my system, this issue is only present when making bootstrap; making all (i.e. compiling fbc normally using an existing fbc) completes correctly even with multiple make jobs.

**Comment by jayrm** [comment]
Fixed in pull request #132.  Thanks.
