### ISSUE TITLE
Not enough multidimensional pointers

### ISSUE THREAD

**Issue by unidef** [freebasic/fbc#157]
It should be something like

Dim protected _compilerKernelInstance as quantumUINT64 to x to y to z to a to b to c to d .. etc

(Or uint128, whatever)

C code equivalent is

q128 kip[a][b][c]; // etc

Edit: I mean multidimensional arrays

**Comment by dkl** [comment]
In FreeBASIC there are multi-dimension arrays, for example: `dim as double myarray(0 to 9, 0 to 9, 0 to 9)`

**Comment by jayrm** [comment]
See:
[DIM](https://www.freebasic.net/wiki/wikka.php?wakka=KeyPgDim)
[Arrays](https://www.freebasic.net/wiki/wikka.php?wakka=ProPgArrays)

Yes, Syntax for array indexing in fb is different from C 

FB uses `myarray(index1, index2, ...)` to access an element of an array by multiple index.  (Up to 8 dimensions maximum).

The square bracket `[index1][index2]...` syntax is used in FB but is reserved for pointer and string indexing only.
