### ISSUE TITLE
Makefile in Linux ends up in error

### ISSUE THREAD

**Issue by eridal** [freebasic/fbc#18]
Hey all, 

I'm trying to install the freebasic environment, but the official makefile ends up with errors -- it assumes I already have the fbc installed, which I think is bootstrapped

Also the official guide points to download from sourceforge, which I don't trust as it bundles spyware .. 

- do I'm doing something wrong?
- is there any other source where to download?

I'd love to download and build from sources, no binaries at all.

**Comment by dkl** [comment]
Hello,

the FreeBASIC compiler is self-hosting (written in FreeBASIC itself), so when building from sources it needs a working fbc.

The project's main download site is indeed at Sourceforge:
http://sourceforge.net/projects/fbc/files/

The downloads are also made available by various other people, e.g. at:
http://www.freebasic-portal.de/downloads/aktuelle-compiler/

**Comment by eridal** [comment]
Too bad the only official downloads are binaries over a non-secure connection (http), I really wanted to install freebasic, but given the security concerns the current state raises, I cannot do so in a safe way.

Also, please consider moving the downloads to github, as sourceforge injects adware on the installers.

Anyways, thanks for your reply!

**Comment by dkl** [comment]
Perhaps the latest addition of precompiled compiler sources (bbeeb5ba3ebd565e336e42d4784317f98e3162dc) will be useful for you too; doing ```make bootstrap``` should produce an fbc binary without needing one.

I'm not sure about offering downloads elsewhere. If it's not too much work, then (at least some) of the prebuilt binary packages can surely be uploaded on Github too though.

The fbc project on Sourceforge did not opt-in to Sourceforge's adware installer, so at least from that point of view the downloads from there should always be the proper ones.

**Comment by freebasic** [comment]
Aren't there hashes of the binaries? Just post it here on (Secure) 
github, then you can verify it when you download :)

**Comment by dkl** [comment]
Allright, I've uploaded sha1sums.txt.gz for the 1.01.0 and 1.02.0 releases here, and linked to the download site at SourceForge. That should do it.

Furthermore, we have a FreeBASIC-1.02.0-source-bootstrap.tar.xz download now afterall, which allows bootstrapping an fbc via `make bootstrap`.

**Comment by eridal** [comment]
thanks sooo much!
