### ISSUE TITLE
enable framebuffer driver for arm

### ISSUE THREAD

**Issue by stephaneweg** [freebasic/fbc#192]
in the raspberry pi, we want to use the framebuffer driver, to enable graphic mode without x11
the header files disables this drivers for the arm, because there is inline assembly.

this inline assembly is only used for the 4 bit per pixel mode, but we will use the 16bpp mode, so we could put the content of this method in comment for the arm target, instead of disable the driver

**Comment by jayrm** [comment]
framebuffer enabled and 4-bits-per-pixel blitter added in #256 
Closing issue as resolved.
