### ISSUE TITLE
Is Free Basic compiler 100 % compatible with RAPID Q?

### ISSUE THREAD

**Issue by JanuszChmiel** [freebasic/fbc#213]
Dear specialists,
I Am visually impaired and because I have issues while designing forms by specifiing object position values, I would like to know, if I could simply use rapidq.inc file with Free Basic compiler. I do not know, but I think, that there are alligment constants and that I could use listboxes, nubuttons without number specifrication of width and hewight. Or those compilers Rapidq and Free Basic compiler are very different so I can not simply use my favourite Rapidq language and its .inc files with Free Basic compiler?
Nobody have created .inc file for Free Basic which would simply allow Me to use GUi based commands without adding object position values. I Am very sorry for this question, but I think, that you would inform

**Comment by rversteegen** [comment]
Hello,
I'm not familiar with RapidQ but I had a look. While the syntax is very similar to FB, there are still various differences. I think it would be possible to port a lot of code one language to another by hand quite quickly, but code that's part of the GUI framework depends on the framework, so I assume can't be ported to FB. Some of the .inc files just contain lists of constants, and those can be included directly in FB without modification.
There are also GUI builder tools available for FB. I've never used any of them, but there was a recent forum thread discussing some options [here](https://freebasic.net/forum/viewtopic.php?p=269788#p269788)

**Comment by JanuszChmiel** [comment]
The problem is, that alt available Free Basic compatible GUI designers are
visual. And all available .inc files for Free Basic require object position
values as some argument.
How complex would be to develop new .inc file, which would allow visually
impaired programmers to create GUI app with no need to specify object
position values?

**Comment by rversteegen** [comment]
Sorry, I don't understand. You want to create GUIs but not specify the widget positions in code, nor provide them using a GUI builder? So the positions should be completely automatic?
What's in these .inc files you're talking about? Complete definitions of all the widgets that make up a GUI? In what form? I tried looking for RapidQ documentation, but couldn't easily figure it out.  As far as I can tell, .inc files are just like .bi files for FB, so they can and do contain anything.

**Comment by JanuszChmiel** [comment]
Yes. I want to create GUIs but not specify the widget positions in code. 
And to make programmers work as simple as possible, alteast for edit,
Button, listbox, Radio button, Checkbox, menu.
No other Windows object types. I would really code if somebody kind would
create such module it would be really A task, which will have The sense for
many visually impaired programmers.

**Comment by rversteegen** [comment]
So you are just asking for an easy to use FreeBasic GUI library that can layout widgets automatically and supports at least those widgets? In other words, you just want something with features comparable to RapidQ, and your question about inc files is irrelevant?

Unfortunately I can't answer your question, because I'm not familiar with any of the GUI frameworks available for FB. I recommend you ask on the [FreeBasic forums](https://freebasic.net/forum/) instead, many more people will see your question there. This issue tracker is rarely used for discussion.

**Comment by JanuszChmiel** [comment]
Yes, you have understood Me perfectly.
I Am very sorry for my unrelevant .inc question. I have wrongly understood
how Rapidq xcompiler work. That alclient altop is very probably The part of
compiler engine.

**Comment by Mr-Swiss** [comment]
The only programming languages I've come across so far, that offer something similar to what is described here (e.g. sizing controls by clicking arrows, on a presized grid) are graphical programming tools (best known one: NI-LabView) which is however, heavily inclined towards process-control, either virtual (simulation only) or real (HW in the loop). It is however very, very expensive > 4 K$.
There are cheaper alternatives but, they too, have drawbacks like no Real-Time functionality.
 
I currently don't know about any multi-purpose langage (typed or graphical), that supports similar functionality (with or without libraries).

**Comment by JanuszChmiel** [comment]
So by other words, FNX Basic is really unique treasure. It can do that
thanks to VCL unit from Borland.
And I also know about big modules for Autoid. One programmer have got
special task from The US goverment. He has work on The department for
accessibility and he has created special module which automatically
calculate object positioning by using defined norm from Microsoft
corporation.

Here is The direct link to download .zip archive with The module and sample
source code.

https://codeload.github.com/jamalmazrui/Layout_by_Code/zip/master

If his code could be ported to Free Basic, but I know, that it is not easy.
Autoid uses more internal commands for GUI creation which are very probably
not available for Free Basic.

**Comment by Mr-Swiss** [comment]
Since there are absolutely NO predefined GUI routines in FreeBASIC (only a rudimental graphics sub-system), it whould be a monumental task, to port anything like that ...
As a comparison: FreeBASIC is almost as 'low level' as pure C code (without external libraries).

**Comment by JanuszChmiel** [comment]
aYes I Am understanding you. It is like a little C compiler. So you can
close this topic and thank you very much for yours debate.

**Comment by JanuszChmiel** [comment]
Does somebody of us know, if Microsoft offer some paied digital signature,
which developer can use to sign its .exe so Windows Defender will stop to
analyse such signed .exe apps so deeply? Because I will have to use FNX
Basic. It contain graphical engine, many complex other thinks and I Am not
sad, that my apps will be larger than 1 MB. But I Am afraid, that powerful
Microsoft CORP want to convince all developer that they rather should use
their official compilers such as included with WIndows SDK.
But those IDES are good for visually impaired developers, who own expensive
hardware, more than 32 GB of RAM, more than 3,8 GH/Z CPU and multi raid
harddisks. Only this hardware power can enable them to use their complex
IDES with big load size, many various files which must be loaded to RAM,
inter process commmunication with screen readers, which allocates some RAM,
more CPU cycles, ETC.

**Comment by rversteegen** [comment]
You want to avoid Windows Defender analyzing your .exe file, to reduce CPU usage? Surely that can't be right. Are you instead asking about how to get around Windows SmartScreen blocking unsigned .exes? Well, even if you buy a certificate and sign it, your .exe will still be blocked by default if it isn't common.

**Comment by JanuszChmiel** [comment]
Yes, I have thought, that when exe app will be digitally signed, that smart
screen will not warn The user.
So by other words. If I want to avoid such behaviour I would had to publish
on Windows store, but I Am afraid, that it is not possible to store other
apps on Windows store than apps which have been compiled by one of The tools
for Visual studio from Microsoft.

**Comment by retsyo** [comment]
@JanuszChmiel
you can use IUP which does not require you to specify the location and size of widgets. [here](https://fossies.org/linux/FreeBASIC/examples/GUI/IUP/textbox.bas) is an example. The IupVbox and IupHbox do the layout for you.

But let's talk something beyond. If a GUI lib can get&set the size and coordinates of widgets, and supply `resize` event, then we can make your application auto-layout widgets. Yes, maybe we do not need to resize the frame every time, but this auto-layout also sets the position of widgets. 

There are 2 hard infrastructures to be implemented for freebasic, one is the `Cassowary constraint solving algorithm`, the other is a plan to describe constraints of widgets and translate the description into `Cassowary constraint solving algorithm`.

[My code](https://github.com/retsyo/nim-vcl-test/blob/master/test_kiwi.nim) is an example but in another computer language.

**Comment by JanuszChmiel** [comment]
Dear retsyo,
Could you provide A FreeBasic compatible download of 
IupVbox and IupHbox 
Please where are The FreeBasic compatible modules of this toolkit?
I have found The varinat for Lua and C but not for Free Basic.
Thank you very much.

**Comment by JanuszChmiel** [comment]
OH I Am very sorry. Sure, The Free Basic modules area available in /inc
folder.
So I can start to experiment.
Thank you very much for yours professional answer.

**Comment by JanuszChmiel** [comment]
But I have got stuck. Where to get precompiled Win32 bbinaryes?
On sourceforge, there are empty files sub categoryes.

**Comment by retsyo** [comment]
no, all file lives here https://sourceforge.net/projects/iup/files/3.29/Windows%20Libraries/

however I forgot whether freebasic support static or dynamic library, or both

**Comment by rversteegen** [comment]
Sorry for my late reply...

> Yes, I have thought, that when exe app will be digitally signed, that smart screen will not warn The user.

Signing your .exe is apparently not enough, I think Smart Screen will continue to warn users about the file if few users have installed your program, until it becomes common.

> So by other words. If I want to avoid such behaviour I would had to publish on Windows store, but I Am afraid, that it is not possible to store other apps on Windows store than apps which have been compiled by one of The tools for Visual studio from Microsoft.

Distributing via Windows Store does get around Smart Screen (I think). But it isn't necessary to use Visual Studio to create a store app. Apparently mingw can do it, or you can use the new alterntative clang-based VC++ toolchain: https://stackoverflow.com/questions/12909139/can-windows-store-applications-be-built-with-mingw

**Comment by Mr-Swiss** [comment]
> however I forgot whether freebasic support static or dynamic library, or both
FBC can hadle both static as well as dynamic libraries.
In IUP downloads pick *statc* or *dynamic* subdir first, then download the appropriate bitness 32 or 64, with the Mingw specifier (NOT the VC stuff) since the used C compiler (in 64 bit FBC) is GCC.
As a Tip: most FB people prefer static linking (includes everything into .exe). A 64 bit .exe with static IUP is at least 800 KB in size.
More info can be found in the Forum: https://www.freebasic.net/forum/viewtopic.php?f=14&t=28531&hilit=IUP

**Comment by JanuszChmiel** [comment]
Oh thank you for yours kind access to my plea. Thank all of us who are so
kind to Me and thank you all of you, who are participating in this debate.
FreeBasic is very promsing programming language. Produces reliable machine
code apps, which produces low memory foot print. Yes, I also prefer
statically linked .exe apps. For example MyFbFramework can be also linked to
.exe stacically.
By other words, there are allready two useful and fully functioning GuI
toolkits for visually impaired programmers of Free Basic.
MyFbFramework and IUP. So Borland Delphi developers had their VCL unit and
FreeBasic developers can use for example those two toolkits.
Thank you again for yours help and support. Free Basic have very good
potentil to serve as Ole automation client for various apps which support
object model. Such as Word.
In some cases, screen readers developers do not want to implement some
useful tasks which could allow visually impaired users to use Word or Excel
according to their needs. And in those cases, programming language which
support ole automation is very handy solution for smart visually impaired
man or woman.

**Comment by JanuszChmiel** [comment]
Thank you very much for yours professionally published advice. Thanks to
yours advice and thanks to The forum link, I have allready tested several
apps which are being used IUP. In my case, my .exe have more than 1 MB 200
KBm, since I AM building it by using VisualFBEditor.1.2.2. Or do you think,
that The big syze is not The cause hat I Am using VisualFBEditor.1.2.2?
 
Finding fully accessible and working FB IDE is not easy task.
Some IDES lack screen readers support while using Editable field. Some have
strange and complex GUI.

**Comment by JanuszChmiel** [comment]
I have chosen WINFB suite as The most accessible FreeBasic IDE. GUI is very
accessible, many objects are focusable by using TAB, SHIFT+TAB. And I could
test IUP by using this IDE very well. The most important fact is, that Winfb
suite support editable field with code without issues. With only little
exception. Line numbers are not spoken by screen reader. But when compared
with other available FreeBasic IDES, it is really only cosmetic issue.
I can select with SHIFT key, I can browse char by char, word by word without
issues.
So I must only leanr and develop.

**Comment by retsyo** [comment]
since you have mentioned VCL, https://github.com/ying32/govcl/ can be used in freebasic too since it is a re-wrapped library based on VCL/LCL but supplies C header. However, you have to make the interface for freebasic by yourself. It runs on multi-OS, and the DLL is < 2M on windows platform

**Comment by jayrm** [comment]
@JanuszChmiel, thank-you for your report on the issue.  It seems beyond the scope to FreeBASIC directly.  Closing.  Thanks.
