### ISSUE TITLE
Do you plan to extend yours compiler by adding support for aarch64 cpus?

### ISSUE THREAD

**Issue by JanuszChmiel** [freebasic/fbc#215]
I Am aware, that generating machine code instructions which produces reliable executable is The most complex task for every programmer. You have reached this goal by supporting X86 and X64 Bit INTEL compatible CPUS. Do you plan to add support for ARM cpus? I know, that generating Assembly instructions would be next complex task. So I Am only kindly asking you. If no, I will respect it, bešcause it is always much more better to support one CPU 100 % reliably than adding support for many CPUS but resulting machine code would produce chaos when run in target system.
Thank you very muct for yours answer.

**Comment by rversteegen** [comment]
I am not really part of the FreeBASIC developer team, but don't know of anyone working on ARM assembly output.

But FreeBASIC already supports (little-endian) ARM and ARM64 CPUs via the C (GCC) emitter.

**Comment by JanuszChmiel** [comment]
aOh it would be excellent.
Could you write Me some example command line which would generate ARM64 Bit
compatible executable for Linux?
Because I have found out excellent GUI toolkit for Free Basic compiler. It
support Win32 API compatible GUi so screen readers can perfectly work with
app which have been created by it. And this GUI toolkit even support GTK3
libraries, which are fully compatible with At-SPI accessibility libraries
and with Orca screen reader for Linux.
Toolkit even do not strictly enforce develper to specify object position
values in Pixels for every object. Adjectives can be used to specify
approximate position altop, left, ETC. Sure, sgihted will use visual
designer and his GUi will be always much more nicer than myne one. But I Am
glad, that there is so good toolkit. All of its GUi elements are really
accessible with screen readers. So screen readers developers do not have to
modify screen readers source code to support it.
The GUi toolkit name is
MyFbFramework

**Comment by rversteegen** [comment]
Just get a build of freebasic for your device, and it will create executables for that device.

I believe AArch64 cpus are backwards compatible with 32-bit ARMs like armv7a, so if your operating system supports it, maybe you can just use a 32-bit ARM freebasic build.

You can get various builds of FB from http://users.freebasic-portal.de/stw/builds/ including linux-armv6-rpi and linux-armv7a-hf-debian, and in the _manual directory is a 4-year-old ARM64 build.

**Comment by czsgaba** [comment]
63/5000
If you are using a Debian derivative, see the Deb package fo AArch64 or ARMhf here:

https://www.freebasic.net/forum/viewtopic.php?f=5&t=25266&p=227176#p227176

**Comment by JanuszChmiel** [comment]
Thank you very much for yours advice.
Free Basic is much easier as Vala or C so it would be A nice programming
tool not only for visually impaired Linux programmers.
