### ISSUE TITLE
function getMouse() seems broken on Win10 when using the Console Mode (screen 0)

### ISSUE THREAD

**Issue by ghost** [freebasic/fbc#216]
running the sample code from the manual 1.0.7 about getMouse()
the return of x, y, buttons works when setting any screenres but it doesnt return anything when in a console window. it seems to have worked on win7... something must have changed for win10

**Comment by jayrm** [comment]
Confirmed that behaviour is different between win 7 & win 10 and that #245 appears to correctly handle both versions.

**Comment by jayrm** [comment]
fixed by #245
