### ISSUE TITLE
rtlib leaks thread local data

### ISSUE THREAD

**Issue by adeyblue** [freebasic/fbc#246]
The thread local data stored in rtlib can be left allocated in certain situations. That stored by Dir is the most easily noticable. Open Task Manager to the Details tab (Win10) or Processes tab (<=Win 7), turn on the Handles column, and run the code below. The count of handles will rise as the reported thread count does (well, as long as %ProgramFiles% has at least one directory in it).

It happens as Dir only closes the directory enumeration handle when everything has been enumerated. If you stop before the end, it is never closed. The same thing looks to happen with fds on Linux (I can't test on there, but the Linux Dir code is patterned the same way as the Windows one).

Memory can also leaked by the Input statement which stashes the typed input in a thread local structure (src/rtlib/con_input.c). 

    #include "crt/stdlib.bi"
    #include "dir.bi"
    
    Dim Shared g_threadCnt as Long = 0
    Dim Shared g_countMutex as Any Ptr
    Dim Shared g_stop As Long = 0
    
    #ifdef __FB_WIN32__
    #include "windows.bi"
    
    Const ENV_VALUE As String = "ProgramFiles"
    
    #else
    
    Const ENV_VALUE As String = "HOME"
    
    #endif
    
    Private Function IncrementLong(ByRef count As Long) As Long
    
        MutexLock(g_countMutex)
        count += 1
        Function = count
        MutexUnlock(g_countMutex)
    
    End Function
    
    Private Sub ThreadProc(ByVal p As Any Ptr)
    
        Dim threadId As Long = IncrementLong(g_threadCnt)
        Dim pDirpath As String Ptr = p
    
        Dim folder As String = Dir(*pDirPath, fbDirectory)
    
        If Len(folder) = 0 Then
           Print "Dir failed in thread id " & Str(threadId)
           IncrementLong(g_stop)
        End if
    
    
    End Sub
    
    #define THREADS_PER_LOOP 32
    
    Private Sub Setup()
    
        Dim zDirPath As ZString Ptr = getenv(ENV_VALUE)
        If zDirPath = Null Then
            Print "Couldn't find env var " & ENV_VALUE
            Exit Sub
        End If
    
        Dim dirSpec As String = *zDirPath & "/*"
        Dim threads(0 to (THREADS_PER_LOOP - 1)) As Any Ptr
        Dim i As Long = 0
        Dim created As Long = 0
        Dim loopCount As Long = 0
    
        Print "DirSpec = " & dirSpec
    
        g_countMutex = MutexCreate()
    
        Do
            For i = 0 To (THREADS_PER_LOOP - 1)
                threads(i) = ThreadCreate(@ThreadProc, @dirSpec)
                If threads(i) = 0 Then
                   Print "Failed creating thread no " & Str((loopCount * THREADS_PER_LOOP) + i)
                   Exit For
                End If
                created = i
            Next
            For i = 0 To created
                ThreadWait threads(i)
            Next
            If created <> (THREADS_PER_LOOP - 1) Then
                Exit Do
            End If
            loopCount += 1
            If (loopCount Mod 10) = 0 Then
                Print "Threads done: " & Str(loopCount * THREADS_PER_LOOP)
    #ifdef __FB_WIN32__
                ' Stop the thread stacks from ballooning memory usage
                SetProcessWorkingSetSize(INVALID_HANDLE_VALUE, cast(SIZE_T, -1), cast(SIZE_T, -1))
    #endif
            End If
        Loop While (Inkey = "") AndAlso (g_stop = 0)
    
        MutexDestroy(g_countMutex)
    
    End Sub
    
    Setup()

**Comment by jayrm** [comment]
fixed in #247
