### ISSUE TITLE
cannot find install.sh

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [freebasic/fbc#266]
To do on Fedora 33, AArch64 

sudo ./install.sh -i

I do not find in the git clone'd master that file.

**Comment by jayrm** [comment]
In a cloned repository or source package you can find it at `./contrib/unix-installer/install.sh`
[contrib/unix-installer/install.sh](https://github.com/freebasic/fbc/blob/master/contrib/unix-installer/install.sh)

Or for any file can search for it: `$ find . -iname 'install.sh'`

Usually though, if you are building fbc yourself from cloned repository should also be able to:
`$ sudo make install`
to install the compiler, libraries, etc, to the system directories.

The `install.sh` file is copied to the top directory only when making the binary packages.

**Comment by LutzWeischerFujitsu** [comment]
Thanks. 
'sudo ./contrib/unix-installer/install.sh -i' reports 'install: cannot stat './bin/fbc': No such file or directory'. 'bin' is empty. 
'sudo make install' reports 

FBC src/compiler/obj/linux-aarch64/ast-gosub.o
FBC src/compiler/obj/linux-aarch64/ast-helper.o
/bin/sh: fbc: command not found
FBC src/compiler/obj/linux-aarch64/ast-misc.o
/bin/sh: fbc: command not found
FBC src/compiler/obj/linux-aarch64/ast-node-addr.o
/bin/sh: fbc: command not found
FBC src/compiler/obj/linux-aarch64/ast-node-arg.o
/bin/sh: fbc: command not found
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-gosub.o] Error 127
make: *** Waiting for unfinished jobs....
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-helper.o] Error 127
FBC src/compiler/obj/linux-aarch64/ast-node-assign.o
/bin/sh: fbc: command not found
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-misc.o] Error 127
FBC src/compiler/obj/linux-aarch64/ast-node-bop.o
/bin/sh: fbc: command not found
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-node-addr.o] Error 127
FBC src/compiler/obj/linux-aarch64/ast-node-branch.o
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-node-arg.o] Error 127
/bin/sh: fbc: command not found
/bin/sh: fbc: command not found
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-node-assign.o] Error 127
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-node-bop.o] Error 127
make: *** [makefile:586: src/compiler/obj/linux-aarch64/ast-node-branch.o] Error 127

**Comment by jayrm** [comment]
The source code for freebasic compiler 'fbc' is written in freebasic language itself.  So you will need a working fbc compiler already installed to compile the fbc compiler.

Looks like fedora 33 has a package available:
https://fedora.pkgs.org/33/rpm-sphere-aarch64/freebasic-1.07.1-1.aarch64.rpm.html

In which case you would
- install fedora 33 - freebasic 1.07.1 package
- get latest freebasic 1.08 from git clone
- try make && make install from source

Information about bootstrapping the compiler: https://www.freebasic.net/wiki/DevBootstrap
Sorry, I don't think any of the main freebasic developers have an Aarch64 platform to test on so information about aarch64 is limited (or non-existent).

If you do have have success building fbc, please considering offering some feedback or information to update the documentation about the Aarch64 target.

**Comment by jayrm** [comment]
Official ARMv7 and ARMv8 packages released
See: https://www.freebasic.net/forum/viewtopic.php?t=29054

Packages built and tested with:
raspian9-arm (on a RPI 3)
ubuntu-20.10-aarch64 (on a RPI 4)

bootstrap package now includes arm and aarch64 targets
