### ISSUE TITLE
fbc fails on Hello World 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [freebasic/fbc#284]
Thanks. Downloaded from sourceforge and installed AArch64 binary using install.sh -i on Fedora 33. Calling fbc works, but executing Hello World results in 
fbc: /lib64/libtinfo.so.6: no version information available (required by fbc)
hello.bas(1) error 146: Only valid in -lang deprecated or fblite or qb in '10 REM Hello World in BASIC'
hello.bas(2) error 146: Only valid in -lang deprecated or fblite or qb in '20 PRINT "Hello World!"'

**Comment by XusinboyBekchanov** [comment]
For libtinfo.so.6 you can look here: https://www.freebasic.net/forum/viewtopic.php?t=28443
Line numbering is only available in fblite or qb dialects.

**Comment by jayrm** [comment]
@LutzWeischerFujitsu I believe that issue has been answered by @XusinboyBekchanov 

Closing issue
