### ISSUE TITLE
Add support for DragonflyBSD and Solaris

### ISSUE THREAD

**Issue by CretinHo** [freebasic/fbc#285]
Please read these two forum threads:

https://www.freebasic.net/forum/viewtopic.php?f=17&t=29149

https://www.freebasic.net/forum/viewtopic.php?f=17&t=29165

The last thread I posted a patch. I did it in darkness without any guidance, so please don't surprise if it doesn't work at all.

Best regards.

**Comment by countingpine** [comment]
Added in Pull Requests: https://github.com/freebasic/fbc/pull/286 (DragonFlyBSD) and https://github.com/freebasic/fbc/pull/287 (Solaris).
Thanks CretinHo.
