### ISSUE TITLE
Adding a JVM target?

### ISSUE THREAD

**Issue by CretinHo** [freebasic/fbc#307]
I just know that **compiled language which make use of pointers,** could be compiled to JVM bytecode, thanks to this library:

https://asm.ow2.io/

One example is here:

https://github.com/k-john-gough/gpcp

Free Pascal also has a JVM target, but they used Jasmin, an inferior library compared to ASM:

https://wiki.lazarus.freepascal.org/FPC_JVM

Are you interested in such a new target, developers? I know you just wanted to push 1.08 release out. So what about the next version? Could this very target open the door to Android development with FreeBASIC? Free Pascal could be used to develop Android application with the LAMW stack thanks to that FPC_JVM target.

https://wiki.lazarus.freepascal.org/LAMW

**Comment by rversteegen** [comment]
ASM doesn't seem to provide a compile target for (a way to compile) C or other languages. It's a library for outputting JVM bytecode, so it doesn't make a port to the JVM possible unless some other way is found to port FB's rtlib and gfxlib2 (which are written in C) to Java/the JVM.
I think there probably are C-to-Java transpilers and that they would be much more feasible ways to do a port, if there were a reason to want one.

There is an (unmerged) port of FB to Android. You can theoretically even write apps in FB without needing any Java by using [Native Activity](https://developer.android.com/ndk/samples/sample_na), though noone has ported the headers for that and I very much don't recommend it.
