### ISSUE TITLE
SET_GL_SCALE has no effect on Linux

### ISSUE THREAD

**Issue by clebercasali** [freebasic/fbc#320]
Changing 'SCALE' makes no difference. I can even set it to 0, and it will still draw as if SET_GL_SCALE was set to 1.

`#define SCALE 0 ' <-----------

#include "fbgfx.bi"
using fb

#if __FB_VERSION__ = "1.08.0"
   '' remove new 1.08.0 SCREENCONTROL gfx API entry points
   #undef screencontrol
   #undef screencontrol
   #undef screencontrol

   '' add back the 1.07.x and earlier SCREENCONTROL gfx API entry points
   extern "rtlib"
      declare sub ScreenControl overload alias "fb_GfxControl_s" _
         ( _   
            byval what as long, byref param as string = "" _
         )
      declare sub ScreenControl alias "fb_GfxControl_i" _
         ( _
            byval what as long, _
            byref param1 as integer = 0, _
            byref param2 as integer = 0, _
            byref param3 as integer = 0, _
            byref param4 as integer = 0 _
         )
   end extern
#endif

screencontrol(SET_GL_2D_MODE, OGL_2D_MANUAL_SYNC)
screencontrol(SET_GL_SCALE, SCALE)
screenres 320, 200, 32, , GFX_OPENGL

dim as integer w, h, d
dim as string driverName
screeninfo w, h, d, , , , driverName
print driverName & " @ " & str(w) & "x" + str(h) & "x" + str(d)
circle(320\2, 200\2), 90, rgb(200,200,0)

'' You need to poll flip() so the window doesn't become unresponsive
do
sleep( 1, 1 )
flip
loop until( len( inkey() ) )
`

**Comment by jayrm** [comment]
Ah, the `SET_GL_SCALE` issue is due a different bug from the `SCREENCONTROL` bug in #316

This bug with `SET_GL_SCALE` started in commit [0b4598d09bb1c5ae62950da565e4030e7a51c736] while fixing other issues with the opengl scaling.

Will fix soon.

**Comment by jayrm** [comment]
SET_GL_SCALE for linux:
fixed in fbc-1.08.1 [590fcb608fc5e7df961f2b0cc769f867539f500b]
fixed in fbc-1.09.0 [146862f8675cde98141e2f14ec60ac977dabebc6]

Thank-you for the report.
