### ISSUE TITLE
crt0.o

### ISSUE THREAD

**Issue by TrueGodder** [freebasic/fbc#330]
I have to downloaded as.exe in ms-dos, but when I tried to compile my program to do the ackermann function says "a.bas() error 23: cannot find crt0.o, ld: cannot find -lgcc, ld: cannot find -lm". My command was "fbc a.bas -t 4096 -lang qb". Is there a fix to fix that issue?

**Comment by jayrm** [comment]
@TrueGodder, which package and version did you download?

The 'fbc-1.08.1-dos.zip' package is intended to be installed in to the djgpp tool chain.  It contains only the compiler and needs files from the djgpp installation to compile programs.

Try the 'FreeBASIC-1.08.1-dos.zip' standalone package.  It includes 'as' and other needed files and libraries to compile freebasic programs without a djgpp installation.

**Comment by jayrm** [comment]
Issue reproduced in dos-box.  Appears to be the package used.
