### ISSUE TITLE
fblite not working

### ISSUE THREAD

**Issue by Randall-Glass** [freebasic/fbc#344]
fblite not working.

Have tried  lang "fblite" and '$lang: "fblite"

Just not working.

**Comment by jayrm** [comment]
This is related to [Getting error using fblite](https://www.freebasic.net/forum/viewtopic.php?t=29591) on freebasic.net?

`'$lang: "fblite"` and `#lang "fblite"` works for current development builds and releases for at least 10 years.

Take care with the symbol/punctuation characters.

For reference:
- wiki page for [`#lang "fblite"`](https://www.freebasic.net/wiki/KeyPgPpLang)
- wiki page for [`'$lang: "fblite"`](https://www.freebasic.net/wiki/KeyPgMetaLang)
