### ISSUE TITLE
fedora 35 wont run freebasic.

### ISSUE THREAD

**Issue by Plutonium5793** [freebasic/fbc#349]
Ever since I have tried to use freebasic, its use has been problematic.  In fedora there has not been support for -lwebkitgtk-1.0.  It appears that fedora supports webkitgtk-4.0, but that doesn't satify fbc.  
I have installed all the libraries the readme.txt says to install for fedora, but it won't compile fbc programs and says it cannot find lwebkitgtk-1.0.  A few versions ago (both fedora and fbc) I could load an old rpm to limp along, but that no longer works.  Is there any possibility of fixing this dependency problem?

**Comment by 3oheicrw** [comment]
Which fbc program? fbc itself has nothing to do with webkitgtk. Are you trying to compile VisualFBEditor and MyFbFramework? You should ask the developer on his support thread on freebasic forum.

**Comment by Plutonium5793** [comment]
I tried the precompiled version and then compiled it myself.  When I use the resulting fbc with geany on programs that have previously compiled successfully I get
ld: cannot find -lwebkitgtk-1.0 
compilation failed.  
When I search for "webkitgtk" I find that  /usr/include/webkitgtk-4.0 is installed. Under that directory is webkit2.   I know that several fedora versions ago I had the problem, but was able to find an rpm of webkitgtk-1.0 on fedora twenty something (like fedora 28 or so) that I was able to install.  Apparently updating fedora removed the obsolete version.

**Comment by rversteegen** [comment]
It sounds like you have geany set up to pass ` -lwebkitgtk-1.0` to fbc? How are you invoking fbc from geany, and what's the commandline? You can also pass -v to fbc to see the commandline options it passes to ld. As said, fbc does not depend on webkit.

**Comment by Plutonium5793** [comment]
Ok.  I think I found my problem.  I use window9 and it is coughing up that error.  I need to see what can be done.  Thanks,
John
