### ISSUE TITLE
Open Discussions on this repository?

### ISSUE THREAD

**Issue by 3oheicrw** [freebasic/fbc#359]
Have a look at Github Discussions:

https://docs.github.com/en/discussions

I know FreeBASIC already has a forum for itself but Discussions is handy when someone wanted to discuss about the internal of the compiler directly with the developers on this repository. Someone is porting FBC to FreeBSD POWERPC64 and he currently uses the Issues section to discuss about it. I think he could benefit greatly from Discussions.

Update: here he is: https://github.com/freebasic/fbc/issues/290

**Comment by jayrm** [comment]
An already existing forum and an already existing discussion as an issue is enough.
