### ISSUE TITLE
I have a beautiful dream and I wonder if it can come true.

### ISSUE THREAD

**Issue by MOODSKY2002** [freebasic/fbc#362]
FreeBasic can reference c(*.h) files so that you can directly copy (*.h functional modules)+ FreeBasic (logic programming) can be compiled into software, development efficiency greatly improved!

**Comment by rversteegen** [comment]
See [compile-time bindgen for FB](https://www.freebasic.net/forum/viewtopic.php?f=8&t=26175) ... which is what I think you were probably trying to suggest?
dkl is no longer working on [fbbindgen](https://github.com/dkl/fbc/commits/bindgen), and neither is anyone else at the moment.

Until then you can use tools for translating .h files to .bi, such as [fbfrog](https://freebasic.net/forum/viewtopic.php?t=18712).

Please only file clear and specific feature requests as issues.
