### ISSUE TITLE
_FILE_OBJECT bug

### ISSUE THREAD

**Issue by MOODSKY2002** [freebasic/fbc#364]
Status = ObReferenceObjectByHandle(hFile,null,IoFileObjectType,KernelMode,@FileObject,null)
Status Return "STATUS_OBJECT_TYPE_MISMATCH"

I suspect it is the "_FILE_OBJECT" structure type. How can I modify the type?

FB:
typedef struct _FILE_OBJECT {
  CSHORT Type;
  CSHORT Size;
  PDEVICE_OBJECT DeviceObject;
  PVPB Vpb;
  PVOID FsContext;
  PVOID FsContext2;
  PSECTION_OBJECT_POINTERS SectionObjectPointer;
  PVOID PrivateCacheMap;
  NTSTATUS FinalStatus;
  struct _FILE_OBJECT *RelatedFileObject;
  BOOLEAN LockOperation;
  BOOLEAN DeletePending;
  BOOLEAN ReadAccess;
  BOOLEAN WriteAccess;
  BOOLEAN DeleteAccess;
  BOOLEAN SharedRead;
  BOOLEAN SharedWrite;
  BOOLEAN SharedDelete;
  ULONG Flags;
  UNICODE_STRING FileName;
  LARGE_INTEGER CurrentByteOffset;
  volatile ULONG Waiters;
  volatile ULONG Busy;
  PVOID LastLock;
  KEVENT Lock;
  KEVENT Event;
  volatile PIO_COMPLETION_CONTEXT CompletionContext;
  KSPIN_LOCK IrpListLock;
  LIST_ENTRY IrpList;
  volatile PVOID FileObjectExtension;
} FILE_OBJECT, *PFILE_OBJECT;

Mingw:
type _FILE_OBJECT
	Type as _CSHORT
	Size as _CSHORT
	DeviceObject as PDEVICE_OBJECT
	Vpb as PVPB
	FsContext as PVOID
	FsContext2 as PVOID
	SectionObjectPointer as PSECTION_OBJECT_POINTERS
	PrivateCacheMap as PVOID
	FinalStatus as NTSTATUS
	RelatedFileObject as PFILE_OBJECT
	LockOperation as BOOLEAN
	DeletePending as BOOLEAN
	ReadAccess as BOOLEAN
	WriteAccess as BOOLEAN
	DeleteAccess as BOOLEAN
	SharedRead as BOOLEAN
	SharedWrite as BOOLEAN
	SharedDelete as BOOLEAN
	Flags as ULONG
	FileName as UNICODE_STRING
	CurrentByteOffset as LARGE_INTEGER
	Waiters as ULONG
	Busy as ULONG
	LastLock as PVOID
	Lock as KEVENT
	Event as KEVENT
	CompletionContext as PIO_COMPLETION_CONTEXT
end type

**Comment by MOODSKY2002** [comment]
Status = ObReferenceObjectByHandle(hFile,null,IoFileObjectType,KernelMode,@FileObject,null)
Status Return "STATUS_OBJECT_TYPE_MISMATCH"

I suspect it is the "_FILE_OBJECT" structure type. How can I modify the type?

MinGW:
--------------------------------------
typedef struct _FILE_OBJECT {
CSHORT Type;
CSHORT Size;
PDEVICE_OBJECT DeviceObject;
PVPB Vpb;
PVOID FsContext;
PVOID FsContext2;
PSECTION_OBJECT_POINTERS SectionObjectPointer;
PVOID PrivateCacheMap;
NTSTATUS FinalStatus;
struct _FILE_OBJECT *RelatedFileObject;
BOOLEAN LockOperation;
BOOLEAN DeletePending;
BOOLEAN ReadAccess;
BOOLEAN WriteAccess;
BOOLEAN DeleteAccess;
BOOLEAN SharedRead;
BOOLEAN SharedWrite;
BOOLEAN SharedDelete;
ULONG Flags;
UNICODE_STRING FileName;
LARGE_INTEGER CurrentByteOffset;
volatile ULONG Waiters;
volatile ULONG Busy;
PVOID LastLock;
KEVENT Lock;
KEVENT Event;
volatile PIO_COMPLETION_CONTEXT CompletionContext;
KSPIN_LOCK IrpListLock;
LIST_ENTRY IrpList;
volatile PVOID FileObjectExtension;
} FILE_OBJECT, *PFILE_OBJECT;

FB:
_________________________________________________
type _FILE_OBJECT
Type as _CSHORT
Size as _CSHORT
DeviceObject as PDEVICE_OBJECT
Vpb as PVPB
FsContext as PVOID
FsContext2 as PVOID
SectionObjectPointer as PSECTION_OBJECT_POINTERS
PrivateCacheMap as PVOID
FinalStatus as NTSTATUS
RelatedFileObject as PFILE_OBJECT
LockOperation as BOOLEAN
DeletePending as BOOLEAN
ReadAccess as BOOLEAN
WriteAccess as BOOLEAN
DeleteAccess as BOOLEAN
SharedRead as BOOLEAN
SharedWrite as BOOLEAN
SharedDelete as BOOLEAN
Flags as ULONG
FileName as UNICODE_STRING
CurrentByteOffset as LARGE_INTEGER
Waiters as ULONG
Busy as ULONG
LastLock as PVOID
Lock as KEVENT
Event as KEVENT
CompletionContext as PIO_COMPLETION_CONTEXT
end type

**Comment by rversteegen** [comment]
You can edit your posts, you don't need to double post.

Please ask your questions on the forums or elsewhere (e.g. Discord) rather than here.

I wish you would clearly state what your issue is about instead of making us figure it out. I see that the FB type is missing the last three members:
```
KSPIN_LOCK IrpListLock;
LIST_ENTRY IrpList;
volatile PVOID FileObjectExtension;
```
If you want you can try adding these to the FB type, but that seems to be irrelevant to your problem, because `ObReferenceObjectByHandle` does not receive an instance of this type, it passes back a pointer to it.

According to the documentation:
```
STATUS_OBJECT_TYPE_MISMATCH | The ObjectType parameter specifies the wrong object type for the object that is identified by the Handle parameter.
```

**Comment by MOODSKY2002** [comment]
I'm terribly sorry if I might have asked the question incorrectly
Now we are trying to use FB learning to drive development
ObReferenceObjectByHandle return STATUS_OBJECT_TYPE_MISMATCH
I check that _FILE_OBJECT is added against the VC declaration
KSPIN_LOCK IrpListLock;
LIST_ENTRY IrpList;
volatile PVOID FileObjectExtension;
Still at STATUS_OBJECT_TYPE_MISMATCH
FB does not seem to support __volatile now
The question is: could __volatile have this effect? (I've been using BASIC so I don't understand the importance of __volatile)

**Comment by rversteegen** [comment]
Right, FB does not support `volatile`, but it doesn't affect the layout or datatypes of a structure, it only affects how the C or C++ compiler accesses the data. (It means that that member of the struct can be changed at any moment by an external process such as an interrupt.) So it's impossible for the kernel to detect whether it's declared volatile.

But as I said, the definition of `_FILE_OBJECT` doesn't matter and according to the documentation `STATUS_OBJECT_TYPE_MISMATCH` means that `IoFileObjectType` is wrong.

**Comment by MOODSKY2002** [comment]
Thank you so much! This is the answer I want to know.
