### ISSUE TITLE
Golang and FreeBasic

### ISSUE THREAD

**Issue by verholom** [freebasic/fbc#391]
I propose to consider adding golang-backend in FreeBasic. The main advantage, it seems to me, is the scheduler and goroutines. The addition of such functionality, it seems to me, would be beneficial FreeBasic

**Comment by jayrm** [comment]
Thank-you for the proposition.  There are no plans to add new backends to fbc compiler at this time, sorry.  Closing this issue.

It is probably a misconception that a different backend would auto-magically give new features and capabilities to the fb user.  This is not the case.  The backends currently used are only intended to utilize the backend's capabilities on the lowest level possible with any features or constructs fully implemented in the front end.
