### ISSUE TITLE
Invalid assignment/conversion, before 'Then' in function returned Const ZString Ptr

### ISSUE THREAD

**Issue by zamabuvaraeu** [freebasic/fbc#424]
I declared a function that takes and returns a constant:
```
Declare Function TestConstZStringPtr( _
	ByVal key As Const ZString Ptr _
) As Const ZString Ptr
```
If you put the function inside the condition and pass Str(number), the code works:
```
If TestConstZStringPtr(Str(265)) Then
End If
```
If you pass Str(variable) and assign the function result to the variable, then the code works:
```
Dim Number As Integer = 0
Dim result As Const ZString Ptr = TestConstZStringPtr(Str(Number))
```
If you pass Str(variable) and put the function inside the condition, the code does not work:
```
' error 181: Invalid assignment/conversion, before 'Then' in 'If TestConstZStringPtr(Str(Number)) Then'
If TestConstZStringPtr(Str(Number)) Then
End If
```

**Comment by jayrm** [comment]
Thank-you for the report

fixed in fbc-1.20.0 see commit [d0201869deeb33d7c4aa980953a4daf6cee411f4]
