### ISSUE TITLE
Can't link to zlib 1.2.11

### ISSUE THREAD

**Issue by novavoon** [freebasic/fbc#60]
C:\FB\fbc -s console "zlib.bas"
C:\FB\bin\win32\ld.exe: skipping incompatible ./zlib1.dll when searching for -lzlib1
C:\FB\bin\win32\ld.exe: skipping incompatible ./zlib1.dll when searching for -lzlib1
C:\FB\bin\win32\ld.exe: cannot find -lzlib1

**Comment by jayrm** [comment]
What version of fbc?  Do you have a 64-bit zlib installed where linker is expecting 32-bit?

**Comment by novavoon** [comment]
nevermind I forgot that I am using MinGW64 to compile my zlib so I expect it to be a 32bit library. Problem solved after using 64bit version of fbc to compile.
