### ISSUE TITLE
Travis-CI build failed on 32-bit targets

### ISSUE THREAD

**Issue by jayrm** [freebasic/fbc#68]
See PR #66 and PR #67

Build fails:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

```
The following packages have unmet dependencies:
 g++-multilib : Depends: cpp (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: g++ (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: g++-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
 gcc-multilib : Depends: cpp (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc (>= 4:4.8.2-1ubuntu6) but it is not going to be installed
                Depends: gcc-4.8-multilib (>= 4.8.2-5~) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by dkl** [comment]
It looks like travis-ci/travis-ci#5670, so I've pushed the changes suggested there on master. Could you rebase your branches on top (or merge master) to retry the build?

**Comment by jayrm** [comment]
Thanks, dkl.  You're amazing.  OK, I rebased #66  & #67 to master and force pushed.  Looks good.
